name: web_app
description: A Flutter app targeting web platforms.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sdkproj:
    path: ../../packages/sdkproj

flutter:
  uses-material-design: true
